import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";

export default function SafetyScreen() {
  return <ScreenContainer className="px-5 pt-4"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}><Text style={styles.kicker}>USE WITH CARE</Text><Text style={styles.title}>Safety & limits</Text><View style={styles.hero}><View style={styles.heroIcon}><IconSymbol name="shield.fill" size={24} color="#FFC857" /></View><Text style={styles.heroTitle}>Awareness, not navigation</Text><Text style={styles.heroBody}>VisionGuide AI helps you become aware of important obstacles around you. It does not tell you exactly where to walk or promise a safe route.</Text></View><Text style={styles.sectionTitle}>What it may do</Text><View style={styles.card}><Text style={styles.cardText}>Identify some visible objects and present a simple cue such as “possible person ahead” or “possible object to your right.”</Text></View><Text style={styles.sectionTitle}>What it cannot promise</Text><View style={styles.card}><Text style={styles.cardText}>It may miss objects, misclassify a scene, react late, or misunderstand distance and direction. Lighting, motion, camera position, and crowded spaces can affect results.</Text></View><Text style={styles.sectionTitle}>Before you walk</Text><View style={styles.checklist}><Text style={styles.check}>01  Keep using your cane, guide dog, or trusted human support.</Text><Text style={styles.check}>02  Treat every cue as information to verify, not an instruction.</Text><Text style={styles.check}>03  Stop using the feature if it distracts you or behaves unexpectedly.</Text></View><Text style={styles.footer}>This V1 is an assistive awareness experiment, not a replacement for mobility training, navigation tools, or professional advice.</Text></ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { paddingBottom: 28 }, kicker: { color: "#37B6FF", fontSize: 11, fontWeight: "800", letterSpacing: 1.5 }, title: { color: "#F5F8FC", fontSize: 30, fontWeight: "800", marginTop: 4, marginBottom: 18 }, hero: { backgroundColor: "#1B2A32", borderRadius: 23, padding: 20, borderWidth: 1, borderColor: "#4E4931" }, heroIcon: { width: 44, height: 44, borderRadius: 15, backgroundColor: "#3A3520", alignItems: "center", justifyContent: "center", marginBottom: 15 }, heroTitle: { color: "#FFC857", fontSize: 22, fontWeight: "800" }, heroBody: { color: "#E4E0D0", fontSize: 15, lineHeight: 23, marginTop: 9 }, sectionTitle: { color: "#F5F8FC", fontSize: 17, fontWeight: "800", marginTop: 22, marginBottom: 9 }, card: { backgroundColor: "#102238", borderRadius: 18, padding: 16, borderWidth: 1, borderColor: "#233A52" }, cardText: { color: "#D9E4EE", fontSize: 14, lineHeight: 21 }, checklist: { backgroundColor: "#102238", borderRadius: 18, padding: 16, gap: 13, borderWidth: 1, borderColor: "#233A52" }, check: { color: "#D9E4EE", fontSize: 14, lineHeight: 21 }, footer: { color: "#7D91A5", fontSize: 12, lineHeight: 18, marginTop: 20 } });
